/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConduitFeaturesArticlesEditArticleData } from './conduit-features-articles-edit-article-data';
/**
 * 
 * @export
 * @interface ConduitFeaturesArticlesEditModel
 */
export interface ConduitFeaturesArticlesEditModel {
    /**
     * 
     * @type {ConduitFeaturesArticlesEditArticleData}
     * @memberof ConduitFeaturesArticlesEditModel
     */
    article?: ConduitFeaturesArticlesEditArticleData;
}
