/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConduitFeaturesCommentsCreateCommentData
 */
export interface ConduitFeaturesCommentsCreateCommentData {
    /**
     * 
     * @type {string}
     * @memberof ConduitFeaturesCommentsCreateCommentData
     */
    body?: string | null;
}
