/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConduitDomainComment } from './conduit-domain-comment';
import { ConduitDomainPerson } from './conduit-domain-person';
/**
 * 
 * @export
 * @interface ConduitDomainArticle
 */
export interface ConduitDomainArticle {
    /**
     * 
     * @type {string}
     * @memberof ConduitDomainArticle
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConduitDomainArticle
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConduitDomainArticle
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConduitDomainArticle
     */
    body?: string | null;
    /**
     * 
     * @type {ConduitDomainPerson}
     * @memberof ConduitDomainArticle
     */
    author?: ConduitDomainPerson;
    /**
     * 
     * @type {Array<ConduitDomainComment>}
     * @memberof ConduitDomainArticle
     */
    comments?: Array<ConduitDomainComment>;
    /**
     * 
     * @type {boolean}
     * @memberof ConduitDomainArticle
     */
    favorited?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConduitDomainArticle
     */
    favoritesCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConduitDomainArticle
     */
    tagList?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ConduitDomainArticle
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ConduitDomainArticle
     */
    updatedAt?: Date;
}
