/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConduitFeaturesUsersCreateUserData } from './conduit-features-users-create-user-data';
/**
 * 
 * @export
 * @interface ConduitFeaturesUsersCreateCommand
 */
export interface ConduitFeaturesUsersCreateCommand {
    /**
     * 
     * @type {ConduitFeaturesUsersCreateUserData}
     * @memberof ConduitFeaturesUsersCreateCommand
     */
    user?: ConduitFeaturesUsersCreateUserData;
}
