/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConduitDomainPerson } from './conduit-domain-person';
/**
 * 
 * @export
 * @interface ConduitDomainComment
 */
export interface ConduitDomainComment {
    /**
     * 
     * @type {number}
     * @memberof ConduitDomainComment
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ConduitDomainComment
     */
    body?: string | null;
    /**
     * 
     * @type {ConduitDomainPerson}
     * @memberof ConduitDomainComment
     */
    author?: ConduitDomainPerson;
    /**
     * 
     * @type {Date}
     * @memberof ConduitDomainComment
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ConduitDomainComment
     */
    updatedAt?: Date;
}
