/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConduitFeaturesArticlesEditArticleData
 */
export interface ConduitFeaturesArticlesEditArticleData {
    /**
     * 
     * @type {string}
     * @memberof ConduitFeaturesArticlesEditArticleData
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConduitFeaturesArticlesEditArticleData
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConduitFeaturesArticlesEditArticleData
     */
    body?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConduitFeaturesArticlesEditArticleData
     */
    tagList?: Array<string> | null;
}
